# Generated by Django 4.0.4 on 2022-06-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('notes', models.TextField(max_length=500)),
                ('favorite_food', models.BooleanField(default=False)),
                ('budget_item', models.BooleanField(default=False)),
                ('pantry_staple', models.BooleanField(default=False)),
                ('kid_approved', models.BooleanField(default=False)),
                ('picky_approved', models.BooleanField(default=False)),
                ('eat_alone', models.BooleanField(default=False)),
                ('sick_friendly', models.BooleanField(default=False)),
                ('low_spoons', models.BooleanField(default=False)),
                ('texture_friendly', models.BooleanField(default=False)),
                ('color_friendly', models.BooleanField(default=False)),
                ('arfid_approved', models.BooleanField(default=False)),
                ('diet_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('directions', models.TextField(max_length=500)),
                ('favorite_recipe', models.BooleanField(default=False)),
                ('budget_meal', models.BooleanField(default=False)),
                ('staple_meal', models.BooleanField(default=False)),
                ('kid_approved', models.BooleanField(default=False)),
                ('picky_approved', models.BooleanField(default=False)),
                ('easy_prep', models.BooleanField(default=False)),
                ('sick_friendly', models.BooleanField(default=False)),
                ('low_spoons', models.BooleanField(default=False)),
                ('texture_friendly', models.BooleanField(default=False)),
                ('color_friendly', models.BooleanField(default=False)),
                ('arfid_approved', models.BooleanField(default=False)),
                ('diet_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main_app.food')),
                ('foods', models.ManyToManyField(to='main_app.food')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main_app.recipe')),
                ('recipes', models.ManyToManyField(to='main_app.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
