# Generated by Django 4.0.4 on 2022-06-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='food',
        ),
    ]
